[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "development"
ASSEMBLYAI_API_KEY = "YOUR_ASSEMBLYAI_API_KEY"
GROQ_API_KEY = "YOUR_GROQ_API_KEY"