[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
startCommand = "/app/start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"